{{- if .Values.automatic.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "k8s-ovpn-chart.fullname" . }}
  labels: {{- include "k8s-ovpn-chart.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
spec:
  accessModes:
  {{- range .Values.automatic.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.automatic.persistence.size | quote }}
  {{ include "k8s-ovpn-chart.storageClass" . }}
{{- end }}