apiVersion: v1
kind: Service
metadata:
  name: "{{ include "k8s-ovpn-chart.fullname" . }}-{{ .Values.service.protocol | lower }}"
  labels:
    app.kubernetes.io/name: {{ include "k8s-ovpn-chart.name" . }}
    helm.sh/chart: {{ include "k8s-ovpn-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: "openvpn-{{ .Values.service.protocol | lower }}"
      protocol: {{ .Values.service.protocol }}
      name: "openvpn-{{ .Values.service.protocol | lower }}"
  selector:
    app.kubernetes.io/name: {{ include "k8s-ovpn-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}

---
{{- if .Values.service.fallback }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "k8s-ovpn-chart.fullname" . }}-{{ include "k8s-ovpn-chart.fallbackProtocol" . }}"
  labels:
    app.kubernetes.io/name: {{ include "k8s-ovpn-chart.name" . }}
    helm.sh/chart: {{ include "k8s-ovpn-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: "openvpn-{{ include "k8s-ovpn-chart.fallbackProtocol" . }}"
      protocol: {{ include "k8s-ovpn-chart.fallbackProtocol" . | upper }}
      name: "openvpn-{{ include "k8s-ovpn-chart.fallbackProtocol" . }}"
  selector:
    app.kubernetes.io/name: {{ include "k8s-ovpn-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
{{- end }}
